Create CardTalk component
JetBrains/kotlinconf-app pull request #209
Opened 2024-12-10 20:07 UTC by zsmb13

2024-12-12 07:41 UTC, e5l requested changes

2024-12-12 07:41 UTC, e5l commented on ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/TalkCard.kt
> +    onSubmitFeedback: (Emotion, String) -> Unit,
Please consider split submitting vote and text feedback callbacks

2024-12-12 07:42 UTC, e5l commented
Nice job, please check minor comment

2024-12-13 13:48 UTC, zsmb13 commented on ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/TalkCard.kt
> +    onSubmitFeedback: (Emotion, String) -> Unit,
Makes sense! I've split them into two callbacks and made it remove the existing feedback when tapping it again.

2024-12-13 13:48 UTC, merged