Add stub screens for navigation
JetBrains/kotlinconf-app pull request #215
Opened 2024-12-19 09:04 UTC by kropp

Depends on #214

2025-01-02 15:23 UTC, zsmb13 requested changes

2025-01-02 15:23 UTC, zsmb13 commented on shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/Model.kt
> +}
These new wrapper classes broke the `backend` module, the CI check is failing to compile

2025-01-02 15:23 UTC, zsmb13 commented on shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/AboutApp.kt
> +        Image(painterResource(Res.drawable.arrow_left_24), "back", modifier = Modifier.clickable { navController.popBackStack() })
What's your take on using `popBackStack` vs `navigateUp` in general?

This video reasons for using `navigateUp` instead of `popBackStack`: https://www.youtube.com/watch?v=y2zLFONuk7c

2025-01-07 09:38 UTC, e5l requested changes

2025-01-07 09:38 UTC, e5l commented on shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/App.kt
> +                            StyledText("Start screen")
Please consider extracting string constants

2025-01-09 10:15 UTC, kropp commented on shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/Model.kt
> +}
Fixed in #214

2025-01-09 10:41 UTC, kropp commented on shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/AboutApp.kt
> +        Image(painterResource(Res.drawable.arrow_left_24), "back", modifier = Modifier.clickable { navController.popBackStack() })
Thanks for the link, haven't thought about it before in that way.
As many commenters have pointed out, the issue is not with `popBackStack`/`navigateUp`, but rather with preventing duplicate clicks or, in general, any user actions during the navigation transition.
As our own Ivan Matkov suggested in the comments there, we may check Lifecycle state to prevent this.

On a side note, the Back button behaves differently on iOS, as there you're always navigating inside the app, while on Android with `navigateUp` you may get back to a previous app, depending on how our app was launched.

2025-01-13 07:56 UTC, zsmb13 commented on shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/AboutApp.kt
> +        Image(painterResource(Res.drawable.arrow_left_24), "back", modifier = Modifier.clickable { navController.popBackStack() })
Ah yes, I've also heard the solution with checking the lifecycle. I think the core issue is that people want an API that's a single function and safe to use by default.

I guess they can all write their own `popBackStackSafely()` functions, which are `@Composable` so that they can reach out to the lifecycle to check it before doing a pop.

2025-01-13 08:33 UTC, zsmb13 approved these changes
Added a small bugfix, the rest looks good to me

2025-01-13 15:29 UTC, merged